добавляет решение CounterButton
js-tasks-ru/vue-20230905_neeptoon pull request #5
Opened 2023-09-01 05:32 UTC by neeptoon

2023-09-01 05:33 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-09-04 05:17 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-09-04 17:28 UTC, ShGKme requested changes

2023-09-04 17:28 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button @click="$emit('update:count', count += 1)" type="button">{{ count }}</button>`,
`count` - входной параметр (пропс). Входной параметр нельзя изменять, нельзя присваивать в него новое значение. В консоли браузера можно увидеть предупреждение от Vue.

2023-09-05 18:08 UTC, neeptoon commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  template: `<button @click="$emit('update:count', count += 1)" type="button">{{ count }}</button>`,
ой точно, исправил

2023-09-05 18:10 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-09-05 18:15 UTC, ShGKme approved these changes
Принято

2023-09-05 18:16 UTC, merged